jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      if: matrix.java-version >= 17
      name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
    - continue-on-error: true
      name: Build and check
      run: ./gradlew --no-daemon --info --stacktrace build jacocoTestReport
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: matrix.java-version >= 17 && env.SONAR_TOKEN != ''
      name: Analyze with sonarqube
      run: ./gradlew --no-daemon --info --stacktrace sonarqube -Dsonar.verbose=true
        -Dsonar.login=$SONAR_TOKEN
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: reports (${{ matrix.java-version }})
        path: build/reports
    - continue-on-error: true
      name: Build javadoc
      run: ./gradlew --no-daemon --info javadoc
    strategy:
      matrix:
        java-version:
        - 11
        - 17
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions:
  checks: write
  contents: read
  pull-requests: read
  statuses: read
